# Generated by Django 4.2 on 2023-04-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_autor_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('pendente', 'Pendente'), ('postergado', 'Postergado')], default='pendente', max_length=100)),
                ('categoria', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo')], default='importante', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
