# Generated by Django 4.2 on 2023-04-06 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tarefas_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='categoria',
            new_name='category',
        ),
    ]
