# Generated by Django 4.2 on 2023-04-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_categoria_tarefas_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='date',
        ),
        migrations.AddField(
            model_name='tarefas',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
