# Generated by Django 4.2 on 2023-04-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tarefas_date_tarefas_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
