# Generated by Django 4.2 on 2023-04-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_category_tarefas_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('concluido', 'Concluído'), ('pendente', 'Pendente'), ('adiado', 'Adiado')], default='pendente', max_length=100),
        ),
    ]
