# Generated by Django 4.2 on 2023-04-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_tarefas_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('concluded', 'Concluído'), ('pendeing', 'Pendente'), ('postponed', 'Adiado')], default='pending', max_length=100)),
                ('priority', models.CharField(choices=[('high', 'Alto'), ('average', 'Médio'), ('low', 'Baixo')], default='important', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Tarefas',
        ),
    ]
