# Generated by Django 4.2 on 2023-04-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tasks_delete_tarefas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('high', 'Alto'), ('average', 'Médio'), ('low', 'Baixo')], default='important', max_length=100, verbose_name='Importante'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('concluded', 'Concluído'), ('pendeing', 'Pendente'), ('postponed', 'Adiado')], default='pending', max_length=100, verbose_name='Pendente'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
