# Generated by Django 4.2 on 2023-04-22 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor total')),
                ('status', models.CharField(choices=[('aproved', 'Aprovado'), ('created', 'Criado'), ('reproved', 'Reprovado'), ('pending', 'Pendente'), ('sent', 'Enviado'), ('finalized', 'Finalizado')], default='created', max_length=50, verbose_name='Status do pedido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=190, null=True, verbose_name='Nome do produto')),
                ('variation_produtcts_name', models.CharField(blank=True, max_length=190, null=True, verbose_name='Variação do produto')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Valor')),
                ('quantity', models.PositiveBigIntegerField()),
                ('image', models.CharField(max_length=2000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Id do pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Id do pedido')),
                ('variation_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variation', verbose_name='Id da variação do produto')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Items dos pedidos',
            },
        ),
    ]
