# Generated by Django 4.2 on 2023-04-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Produto')),
                ('descripition', models.TextField(verbose_name='Descrição')),
                ('short_descripition', models.TextField(verbose_name='Descrição Curta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m')),
                ('slug', models.SlugField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do produto')),
                ('promotional_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor do produto promocional')),
                ('type', models.CharField(choices=[('variable', 'Variável'), ('simple', 'Simples')], default='simple', max_length=50, verbose_name='Tipo do produto')),
            ],
        ),
    ]
