# Generated by Django 4.2 on 2023-04-21 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_short_descripition_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, verbose_name='Variação do produto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do produto')),
                ('promotional_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor do produto promocional')),
                ('stock', models.IntegerField(default=1, verbose_name='Quantidade em estoque')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='ID do Produto')),
            ],
            options={
                'verbose_name': 'Variação do Produto',
                'verbose_name_plural': 'Variações dos produtos',
            },
        ),
    ]
